#! /bin/sh

# nightly change background script for cron

export PATH=/bin:/sbin:/usr/bin:/usr/local/bin:/usr/sbin

cd /usr/share/mdm/themes/SwatCS
python mdmbackground.py

# no!!!
#service mdm restart
